import type { Metadata } from 'next';
import {
  AppShell,
  ColorSchemeScript,
  mantineHtmlProps,
  MantineProvider,
} from '@mantine/core';
import { theme } from '@/utils/theme';
import { Footer, Header, Main } from '@/components/layout';
import '@mantine/core/styles.css';
import '@mantine/spotlight/styles.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider theme={theme}>
          <AppShell>
            <Header />
            <Main>{children}</Main>
            <Footer />
          </AppShell>
        </MantineProvider>
      </body>
    </html>
  );
}
