import type { Metadata } from 'next';
import {
  AppShell,
  ColorSchemeScript,
  mantineHtmlProps,
  MantineProvider,
} from '@mantine/core';
import { theme } from '@/utils';
import { Footer, Header, Main } from '@/components/layout';
import { Instrument_Sans } from 'next/font/google';
import '@mantine/core/styles.css';
import '@mantine/spotlight/styles.css';

const instrumentSans = Instrument_Sans({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Nigel Petargue',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' {...mantineHtmlProps} className={instrumentSans.className}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider theme={theme}>
          <AppShell>
            <Header />
            <Main>{children}</Main>
            <Footer />
          </AppShell>
        </MantineProvider>
      </body>
    </html>
  );
}
